## version removed (Compose v2 ignores it)

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - dbdata:/var/lib/mysql

  moodle:
    image: aesr/moodle
    restart: always
    ports:
      - "8090:80"
    environment:
      MOODLE_DB_TYPE: mysqli
      MOODLE_DB_HOST: db
      MOODLE_DB_NAME: moodle
      MOODLE_DB_USER: moodle
      MOODLE_DB_PASSWORD: moodle
    volumes:
      - moodledata:/var/www/moodledata
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  dbdata:
  moodledata:
